<?php

declare(strict_types=1);

use App\Controllers\AdminController;
use App\Controllers\AuthController;
use App\Controllers\HomeController;
use App\Controllers\PageController;
use App\Controllers\StudentController;
use App\Core\Router;

return static function (Router $router): void {
    $router->get('/', [HomeController::class, 'index']);
    $router->get('/home', [HomeController::class, 'index']);
    $router->get('/sobre', [PageController::class, 'sobre']);
    $router->get('/cursos', [PageController::class, 'cursos']);
    $router->get('/eventos', [PageController::class, 'eventos']);
    $router->get('/parcerias', [PageController::class, 'parcerias']);
    $router->get('/privacidade', [PageController::class, 'privacidade']);

    $router->get('/admin/login', [AuthController::class, 'adminLoginForm']);
    $router->post('/admin/login', [AuthController::class, 'adminLogin']);
    $router->get('/admin', [AdminController::class, 'dashboard']);
    $router->get('/admin/dashboard', [AdminController::class, 'dashboard']);
    $router->get('/admin/cursos', [AdminController::class, 'cursos']);
    $router->get('/admin/turmas', [AdminController::class, 'turmas']);
    $router->get('/admin/turmas/show', [AdminController::class, 'showTurma']);
    $router->get('/admin/turmas/novo', [AdminController::class, 'novoTurmaForm']);
    $router->get('/admin/turmas/editar', [AdminController::class, 'editarTurmaForm']);
    $router->post('/admin/turmas/salvar', [AdminController::class, 'createTurma']);
    $router->post('/admin/turmas/atualizar', [AdminController::class, 'updateTurma']);
    $router->get('/admin/alunos', [AdminController::class, 'alunos']);
    $router->get('/admin/alunos/novo', [AdminController::class, 'novoAlunoForm']);
    $router->get('/admin/alunos/editar', [AdminController::class, 'editarAlunoForm']);
    $router->post('/admin/alunos/salvar', [AdminController::class, 'createAluno']);
    $router->post('/admin/alunos/atualizar', [AdminController::class, 'updateAluno']);
    $router->get('/admin/alunos/show', [AdminController::class, 'showAluno']);
    $router->get('/admin/alunos/matricula', [AdminController::class, 'matriculaForm']);
    $router->post('/admin/alunos/matricular', [AdminController::class, 'createMatricula']);
    $router->get('/admin/tarefas', [AdminController::class, 'tarefas']);
    $router->get('/admin/tarefas/lista', [AdminController::class, 'listaTarefas']);
    $router->get('/admin/tarefas/novo', [AdminController::class, 'novaTarefaForm']);
    $router->post('/admin/tarefas/salvar', [AdminController::class, 'createTarefa']);
    $router->get('/admin/tarefas/show', [AdminController::class, 'showTarefa']);
    $router->get('/admin/tarefas/editar', [AdminController::class, 'editarTarefaForm']);
    $router->post('/admin/tarefas/atualizar', [AdminController::class, 'updateTarefa']);
    $router->post('/admin/tarefas/comentario', [AdminController::class, 'createTarefaComment']);
    $router->get('/admin/cursos/novo', [AdminController::class, 'novoCursoForm']);
    $router->get('/admin/cursos/show', [AdminController::class, 'showCurso']);
    $router->post('/admin/cursos/salvar', [AdminController::class, 'createCourse']);
    $router->get('/admin/cursos/editar', [AdminController::class, 'editarCursoForm']);
    $router->get('/admin/cursos/edit', [AdminController::class, 'editarCursoForm']);
    $router->get('/admin/cursos/edit.php', [AdminController::class, 'editarCursoForm']);
    $router->post('/admin/cursos/atualizar', [AdminController::class, 'updateCourse']);
    $router->get('/admin/logs', [AdminController::class, 'logs']);
    $router->get('/admin/visitas', [AdminController::class, 'visitas']);
    $router->get('/admin/visitas/mensal', [AdminController::class, 'visitasMensal']);
    $router->get('/admin/visitas/analytics', [AdminController::class, 'visitasAnalytics']);
    $router->get('/admin/visitas/paginas', [AdminController::class, 'visitasPaginas']);
    $router->get('/admin/cursos/upload', [AdminController::class, 'uploadCursoForm']);
    $router->post('/admin/cursos/upload', [AdminController::class, 'uploadCursoImage']);
    $router->get('/admin/usuarios', [AdminController::class, 'usuarios']);
    $router->get('/admin/usuarios/novo', [AdminController::class, 'novoUsuarioForm']);
    $router->post('/admin/usuarios/salvar', [AdminController::class, 'createUsuario']);
    $router->get('/admin/usuarios/editar', [AdminController::class, 'editarUsuarioForm']);
    $router->post('/admin/usuarios/atualizar', [AdminController::class, 'updateUsuario']);
    $router->get('/admin/modalidade', [AdminController::class, 'modalidade']);
    $router->get('/admin/modalidade/edit', [AdminController::class, 'editModalidadeForm']);
    $router->post('/admin/modalidade/update', [AdminController::class, 'updateModalidade']);
    $router->get('/admin/segmento', [AdminController::class, 'segmento']);
    $router->get('/admin/segmento/edit', [AdminController::class, 'editSegmentoForm']);
    $router->post('/admin/segmento/update', [AdminController::class, 'updateSegmento']);
    $router->get('/admin/setor', [AdminController::class, 'setor']);
    $router->get('/admin/setor/edit', [AdminController::class, 'editSetorForm']);
    $router->post('/admin/setor/update', [AdminController::class, 'updateSetor']);
    $router->get('/admin/nivel', [AdminController::class, 'nivel']);
    $router->get('/admin/nivel/edit', [AdminController::class, 'editNivelForm']);
    $router->post('/admin/nivel/update', [AdminController::class, 'updateNivel']);
    $router->get('/admin/dbase', [AdminController::class, 'dbase']);
    $router->get('/aluno/login', [AuthController::class, 'alunoLoginForm']);
    $router->post('/aluno/login', [AuthController::class, 'alunoLogin']);
    $router->get('/aluno', [StudentController::class, 'dashboard']);
    $router->get('/aluno/perfil', [StudentController::class, 'perfil']);
    $router->post('/aluno/perfil/atualizar', [StudentController::class, 'atualizarPerfil']);
    $router->post('/aluno/matricular', [StudentController::class, 'enroll']);

    $router->get('/area-do-aluno', [StudentController::class, 'dashboard']);
    $router->post('/logout', [AuthController::class, 'logout']);
};
